<?php
/**
 * Location extension for Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @copyright   Copyright (c) 2013 Andrew Kett. (http://www.andrewkett.com)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>

<?php
$locations = $this->getLocations()->getItems();
$total = $this->getTotal();
$url = Mage::getBaseUrl();
$store = Mage::app()->getStore();
if (Mage::helper('ak_locator')->findCurrentCoordinates()) {
    $distanceItems = array();
    Mage::helper('ak_locator')->addDistance($locations);
    foreach ($locations as $location) {
        $distanceItems['id' . $location->getEntityId()] = $location->getDistance();
        $_distance = $location;
    }
    asort($distanceItems);
}
?>
<?php if ($locations) : ?>
    <?php if (count($locations) > 0) : ?>
        <h2><?php echo $this->__('Stores near you') ?></h2>
        <ul class="locations">
            <?php
            $i = 0;

            if (Mage::helper('ak_locator')->findCurrentCoordinates()) {
                $locations = $distanceItems;
            }

            foreach ($locations as $_id => $location):
                $i++;
                if (Mage::helper('ak_locator')->findCurrentCoordinates()) {
                    $id = str_replace('id', '', $_id);
                    $_distance = $location;
                    $location = Mage::getModel('ak_locator/location')->load($id);
                } else {
                    $location = Mage::getModel('ak_locator/location')->load($location->getId());
                    $_distance = $location->getDistance();
                }
                ?>
                <li class="loc-ls-item <?php echo ($i > 4) ? 'hidden' : '' ?>">
                    <article itemscope itemtype="http://schema.org/Place" class="loc loc-teaser"
                             data-id="<?php echo $location->getId(); ?>">
                        <h3 itemprop="name"><?php echo $location->getTitle(); ?></h3>
                        <address itemprop="address">
                            <?php
                            if ($location->getData('locality')) {
                                echo $location->getData('dependent_locality');
                            }
                            ?>
                            <br/>
                            <?php
                            if ($location->getData('locality')) {
                                echo $location->getData('locality') . ', <br/>';
                            }
                            ?>
                            <?php
                            if ($location->getAddress()) {
                                echo $location->getAddress() . ' <br/>';
                            }
                            ?>
                            <?php
                            if ($location->getData('sub_administrative_area')) {
                                echo $location->getData('sub_administrative_area');
                            }
                            if ($location->getData('premise')) {
                                echo ' ' . $location->getData('premise');
                            }
                            if ($location->getData('postal_code')) {
                                echo ' ' . $location->getData('postal_code');
                            }

                            if ($location->getData('sub_administrative_area') || $location->getData('premise')
                                || $location->getData('postal_code')
                            ) {
                                echo '<br/>';
                            }
                            ?>
                            <?php
                            if ($location->getData('phone')) {
                                echo 'Tel: ' . $location->getData('phone');
                            }
                            ?>
                        </address>
                        <p class="approx-km">
                            <?php echo ($_distance > 0) ? $this->__('Approx %s km from you', $_distance) : '' ; ?>
                        </p>
                        <a itemprop="url" href="<?php echo $location->getUrl(); ?>"
                           class="link-detail"><?php echo $this->__('Show Details'); ?></a> | <a
                            href="<?php echo $location->getDirectionsLink(); ?>" target="_blank"
                            class="link-directions"><?php echo $this->__('Get Directions'); ?></a>
                    </article>
                </li>
            <?php endforeach; ?>
        </ul>
        <button onclick="loadmore()" class="button button-white locator_loadmore">
            <?php echo $this->__('Load more stores'); ?>
        </button>

        <script type="text/javascript">
            if(!jQuery('.loc-srch-res-list').find('article.loc-teaser').length || jQuery('.loc-srch-res-list').find('article.loc-teaser').length >= <?php echo $total ?>) {
                jQuery('#loadmore').hide();
            } else {
                jQuery('#loc_total').val(<?php echo $total ?>);
            }
        </script>
    <?php endif; ?>
<?php else : ?>
    <?php echo $this->__('No results found'); ?>
<?php endif; ?>
<script type="text/javascript">
    function loadmore() {
        if (jQuery('.loc-ls-item.hidden').length) {
            var i = 0;
            jQuery(".loc-ls-item.hidden").each(function (index) {
                if (i < 4) {
                    jQuery(this).removeClass('hidden').addClass('show');
                }
                i++;
            });
        }
        if (!jQuery(".loc-ls-item.hidden").length) {
            jQuery(".locator_loadmore").hide();
        }
    }
</script>