<?php
/**
 * Location extension for Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @copyright   Copyright (c) 2013 Andrew Kett. (http://www.andrewkett.com)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>

<?php
$locations = $this->getLocations()->getItems();
$closest = $this->getLocations()->getFirstItem();
$total = $this->getTotal();

if (Mage::helper('ak_locator')->findCurrentCoordinates()) {
    Mage::helper('ak_locator')->addDistance($locations);
    $distanceItems = array();
    foreach ($locations as $location) {
        $distanceItems['id' . $location->getEntityId()] = $location->getDistance();
    }
    asort($distanceItems);
    foreach ($distanceItems as $id => $locationDistance) {
        $id = str_replace('id', '', $id);
        $closest = Mage::getModel('ak_locator/location')->load($id);
        $closest->setData('distance', $locationDistance);
        break;
    }
}
?>

<?php if ($locations) : ?>
    <h2><?php echo $this->__('Closest Store'); ?></h2>
    <div class="closest loc-ls-item">
        <article itemscope itemtype="http://schema.org/Place" class="loc loc-teaser loc-closest"
                 data-id="<?php echo $closest->getId(); ?>">
            <h3 itemprop="name"><?php echo $closest->getTitle(); ?></h3>
            <address itemprop="address">
                <?php
                if ($closest->getData('locality')) {
                    echo $closest->getData('dependent_locality');
                }
                ?>
                <br/>
                <?php
                if ($closest->getData('locality')) {
                    echo $closest->getData('locality') . ', <br/>';
                }
                ?>
                <?php
                if ($closest->getAddress()) {
                    echo $closest->getAddress() . ' <br/>';
                }
                ?>
                <?php
                if ($closest->getData('sub_administrative_area')) {
                    echo $closest->getData('sub_administrative_area');
                }
                if ($closest->getData('premise')) {
                    echo ' ' . $closest->getData('premise');
                }
                if ($closest->getData('postal_code')) {
                    echo ' ' . $closest->getData('postal_code');
                }

                if ($closest->getData('sub_administrative_area') || $closest->getData('premise')
                    || $closest->getData('postal_code')
                ) {
                    echo '<br/>';
                }
                ?>
                <?php
                if ($closest->getData('phone')) {
                    echo 'Tel: ' . $closest->getData('phone');
                }
                ?>
            </address>
            <p class="approx-km"><?php echo $this->__('Approx %s km from you', $closest->getDistance()); ?></p>
            <a itemprop="url" href="<?php echo $closest->getUrl(); ?>"
               class="link-detail"><?php echo $this->__('Show Details'); ?></a> | <a
                href="<?php echo $closest->getDirectionsLink(); ?>" target="_blank"
                class="link-directions"><?php echo $this->__('Get Directions'); ?></a>

            <div itemprop="geo" itemscope itemtype="http://schema.org/GeoCoordinates">
                <meta itemprop="latitude" content="<?php echo $closest->getLatitude(); ?>"/>
                <meta itemprop="longitude" content="<?php echo $closest->getLongitude(); ?>"/>
            </div>
        </article>
    </div>

    <?php if (count($locations) > 1) : ?>
        <h2><?php echo $this->__('Others'); ?></h2>
        <ul class="locations">
            <?php
            $i = 0;
            if (Mage::helper('ak_locator')->findCurrentCoordinates()) {
                $locations = $distanceItems;
            }
            foreach ($locations as $_id => $location) :
                $i++;
                if ($i == 1) {
                    continue;
                }
                if (Mage::helper('ak_locator')->findCurrentCoordinates()) {
                    $id = str_replace('id', '', $_id);
                    $_distance = $location;
                    $location = Mage::getModel('ak_locator/location')->load($id);


                } else {
                    $location = Mage::getModel('ak_locator/location')->load($location->getId());
                    $_distance = $location->getDistance();
                }
                ?>
                <li class="loc-ls-item">
                    <article itemscope itemtype="http://data-vocabulary.org/Place" class="loc loc-teaser"
                             data-id="<?php echo $location->getId(); ?>">
                        <h3 itemprop="name"><?php echo $location->getTitle(); ?></h3>
                        <address itemprop="address">
                            <?php
                            if ($location->getData('locality')) {
                                echo $location->getData('dependent_locality');
                            }
                            ?>
                            <br/>
                            <?php
                            if ($location->getData('locality')) {
                                echo $location->getData('locality') . ', <br/>';
                            }
                            ?>
                            <?php
                            if ($location->getAddress()) {
                                echo $location->getAddress() . ' <br/>';
                            }
                            ?>
                            <?php
                            if ($location->getData('sub_administrative_area')) {
                                echo $location->getData('sub_administrative_area');
                            }
                            if ($location->getData('premise')) {
                                echo ' ' . $location->getData('premise');
                            }
                            if ($location->getData('postal_code')) {
                                echo ' ' . $location->getData('postal_code');
                            }

                            if ($location->getData('sub_administrative_area') || $location->getData('premise')
                                || $location->getData('postal_code')
                            ) {
                                echo '<br/>';
                            }
                            ?>
                            <?php
                            if ($location->getData('phone')) {
                                echo 'Tel: ' . $location->getData('phone');
                            }
                            ?>
                        </address>
                        <p class="approx-km"><?php echo ($_distance > 0) ? $this->__('Approx %s km from you', $_distance) : ''; ?></p>
                        <a itemprop="url" href="<?php echo $location->getUrl(); ?>"
                           class="link-detail"><?php echo $this->__('Show Details'); ?></a> | <a
                            href="<?php echo $location->getDirectionsLink(); ?>" target="_blank"
                            class="link-directions"><?php echo $this->__('Get Directions'); ?></a>

                        <div itemprop="geo" itemscope itemtype="http://schema.org/GeoCoordinates">
                            <meta itemprop="latitude" content="<?php echo $location->getLatitude(); ?>"/>
                            <meta itemprop="longitude" content="<?php echo $location->getLongitude(); ?>"/>
                        </div>
                    </article>
                </li>
            <?php endforeach; ?>
        </ul>

        <script type="text/javascript">
            if (!jQuery('.loc-srch-res-list').find('article.loc-teaser').length || jQuery('.loc-srch-res-list').find('article.loc-teaser').length >= <?php echo $total ?>) {
                jQuery('#loadmore').hide();
            } else {
                jQuery('#loc_total').val(<?php echo $total ?>);
            }
        </script>
    <?php endif; ?>
<?php endif; ?>