<div class="links-wrapper-separators">
	<ul class="links">
		<?php if(!Mage::getSingleton('customer/session')->isLoggedIn()): ?>
			<li class="first hide-below-768 hide-below-480">
				<a title="<?php echo $this->__('Login') ?>" href="<?php echo Mage::getUrl('customer/account/login'); ?>"><?php echo $this->__('Login') ?></a>
			</li>
			<li class="last hide-below-768 hide-below-480">
				<a title="<?php echo $this->__('Register') ?>" href="<?php echo Mage::getUrl('customer/account/create'); ?>"><?php echo $this->__('Register') ?></a>
			</li>
		<?php else: ?>
			<li class="first hide-below-768 hide-below-480">
				<a title="<?php echo $this->__('Logout') ?>" href="<?php echo Mage::getUrl('customer/account/logout'); ?>"><?php echo $this->__('Logout') ?></a>
			</li>
		<?php endif; ?>
	</ul>
</div>