<div class="toplinks">
	<ul class="bullet">
		<li class="first">
			<a title="<?php echo $this->__('My Account') ?>" href="<?php echo Mage::getUrl('customer/account'); ?>"><?php echo $this->__('My Account') ?></a>
		</li>
		<li>
			<a title="<?php echo $this->__('My Wishlist') ?>" href="<?php echo Mage::getUrl('wishlist'); ?>"><?php echo $this->__('Wishlist') ?><span> (<?php echo $this->helper('wishlist')->getItemCount(); ?>)</span></a>
		</li>
		<li>
			<a title="<?php echo $this->__('Compare') ?>" onclick="popWin('<?php echo Mage::helper('catalog/product_compare')->getListUrl() ?>','compare','top:0,left:0,width=820,height=600,resizable=yes,scrollbars=yes')" href="javascript:;"><?php echo $this->__('Compare') ?><span> (<?php echo count(Mage::helper('catalog/product_compare')->getItemCollection()); ?>)</span></a>
		</li>
		<li>
			<a title="<?php echo $this->__('Checkout') ?>" href="<?php echo Mage::helper('checkout/url')->getCheckoutUrl(); ?>"><?php echo $this->__('Checkout') ?></a>
		</li>
		<?php if (!Mage::getSingleton('customer/session')->isLoggedIn()) : ?>
			<li>
				<a title="<?php echo $this->__('Register') ?>" href="<?php echo Mage::getUrl('customer/account/create'); ?>"><?php echo $this->__('Register') ?></a>
			</li>
			<li class="last">
				<a title="<?php echo $this->__('Login') ?>" href="<?php echo Mage::getUrl('customer/account/login'); ?>"><?php echo $this->__('Login') ?></a>
			</li>
		<?php else: ?>
			<li class="last">
				<a title="<?php echo $this->__('Logout') ?>" href="<?php echo Mage::getUrl('customer/account/logout'); ?>"><?php echo $this->__('Logout') ?></a>
			</li>
		<?php endif; ?>
	</ul>
</div>