<?php
  $loc = $this->getLocations()->getFirstItem();
?>
<div class="fixwidth">
	<section class="loc-page" itemscope itemtype="http://schema.org/Place">
		<div class="page-title">
			<h1 itemprop="name"><?php echo $loc->title; ?></h1>
		</div>
		<div class="loc-page-search"><?php echo $this->getChildHtml('form'); ?></div>
		<div class="loc-page-data"><?php echo $this->getChildHtml('info') ?></div>
		<div class="loc-page-map-wrap"><?php echo $this->getChildHtml('map') ?></div>
	</section>
</div>