<?php
$_coreHelper = $this->helper('core');
$checkoutHelper = Mage::helper('onestepcheckout/checkout');
?>
<table class="onestepcheckout-summary">
    <thead>
    <tr>
        <th class="name"><?php echo $this->__('Product'); ?></th>
        <th class="qty"><?php echo $this->__('Qty'); ?></th>
        <th class="total"><?php echo $this->__('Subtotal'); ?></th>
    </tr>
    </thead>
    <?php foreach ($this->getItems() as $item) : ?>
        <tr>
            <td class="name">
                <?php echo $item->getName(); ?>
                <?php if ($checkoutHelper->settings['show_custom_options']) : ?>
                    <?php $options = $item->getProduct()->getTypeInstance(true)
                        ->getOrderOptions($item->getProduct()); ?>
                    <?php if (isset($options['options']) && count($options['options']) > 0) : ?>
                        <ul class="onestepcheckout-custom-options">
                            <?php foreach ($options['options'] as $option) : ?>
                                <li><b><?php echo $option['label'] . ':</b> ' . $option['value']; ?></li>
                            <?php endforeach; ?>
                        </ul>
                    <?php endif; ?>

                    <?php if ($item->getProduct()->isConfigurable()) : ?>

                        <?php
                        $configurableOptions = $item->getProduct()->getTypeInstance(true)
                            ->getSelectedAttributesInfo($item->getProduct());
                        ?>

                        <?php if (is_array($configurableOptions) && count($configurableOptions) > 0) : ?>
                            <ul class="onestepcheckout-custom-options">
                                <?php foreach ($configurableOptions as $option) : ?>
                                    <li><b><?php echo $option['label']; ?>:</b> <?php echo $option['value']; ?></li>
                                <?php endforeach; ?>
                            </ul>
                        <?php endif; ?>

                    <?php endif; ?>

                <?php endif; ?>
            </td>
            <td class="qty"><?php echo $item->getQty(); ?></td>
            <td class="total">
                <?php if ($checkoutHelper->settings['display_tax_included']) : ?>
                    <?php echo $this->helper('checkout')->formatPrice($this->helper('checkout')
                        ->getSubtotalInclTax($item)); ?>
                <?php else : ?>
                    <?php echo $this->helper('checkout')->formatPrice($item->getRowTotal()); ?>
                <?php endif; ?>
            </td>
        </tr>
    <?php endforeach; ?>
</table>
<table class="onestepcheckout-totals">
    <?php foreach ($this->getTotals() as $total) : ?>
        <?php if (!$total->getTitle()) : ?>
            <?php continue; ?>
        <?php endif; ?>
        <tr <?php echo ($total->getCode() === 'grand_total') ? 'class="grand-total"' : '' ?>>
            <td class="title">
                <?php
                $code = $total->getCode();
                $value = $total->getValue();

                if ($code === 'subtotal') {
                    $totalName = $this->__('Subtotal');
                } elseif ($code === 'shipping') {
                    $totalName = $this->__('Shipping');
                    if ($checkoutHelper->settings['display_tax_included']) {
                        $value += $this->getQuote()->getShippingAddress()->getShippingTaxAmount();
                    }
                } elseif ($code === 'grand_total') {
                    $totalName = $this->__('Grand Total(AUD)');
                } elseif ($code === 'tax') {
                    $fullInfo = $total->getFullInfo();
                    if (!empty($fullInfo) && $checkoutHelper->settings['display_full_tax']) {
                        foreach ($fullInfo as $info) {
                            $rates = current($info['rates']);
                            $amount = $info['amount'];
                        }
                        $totalName = $this->__('%s (%s)', $rates['title'], $rates['percent'] . '%');
                    } else {
                        $totalName = $this->__('%s (%s)', 'Standard GST', '10%');
                    }
                } else {
                    $totalName = $total->getTitle();
                }

                echo '<span>' . $totalName . '</span>';
                ?>
            </td>
            <td class="value">
                <?php echo $this->helper('checkout')->formatPrice($value); ?>
            </td>
        </tr>
    <?php endforeach; ?>
</table>
<script type="text/javascript">
    //<![CDATA[
    var total = <?php echo $this->getGrandTotal();?>;
    if (payment.reloadcallback) {
        var url = '<?php echo $this->getUrl('onestepcheckout/ajax/paymentrefresh', array('_secure' => true)); ?>';
        paymentrefresh(url);
        payment.countreload = 0;
        payment.reloadcallback = false;
    }
    //]]>
</script>